### ISSUE TITLE
Errors and such will you be updating this package?

### ISSUE THREAD

**Issue by ruinit** [lad1337/XDM#188]
2015-01-18 17:43:05.826854	
##apikey##N##apikey##e##apikey##w##apikey##s##apikey##n##apikey##a##apikey##b##apikey## ##apikey##f##apikey##i##apikey##n##apikey##a##apikey##l##apikey## ##apikey##s##apikey##e##apikey##a##apikey##r##apikey##c##api

ERROR	   	2015-01-18 17:43:05.831396	
Error during downloadWrapperSingle of Newznab (Default) 
Error: No JSON object could be decoded

Traceback (most recent call last):
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/meta.py", line 160, in outer
    return run(*args, **kwargs)
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/bases.py", line 538, in downloadWrapperSingle
    res = self._searchForElement(*args, **kwargs)
  File "/usr/local/xdm/var/plugins/Indexer/Newznab-de_lad1337_newznab-0_7/Newznab.py", line 71, in searchForElement
    response = r.json()
  File "/volume1/@appstore/xdm/share/XDM/site-packages/requests/models.py", line 629, in json
    return json.loads(self.text or self.content, **kwargs)

**Comment by lad1337** [comment]
the newznab plugin relize on the json output type from newznab not all indexers have a newznab version that supports this
try the NewsnabXML indexer from this repo https://github.com/avdstelt/XDM-plugins

**Comment by ruinit** [comment]
Ty for response I tried what you suggested still have errors.

ERROR	   	2015-01-19 17:45:16.908494	
Error during downloadWrapperSingle of NewznabXML (Default) 
Error: mismatched tag: line 8, column 2

Traceback (most recent call last):
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/meta.py", line 160, in outer
    return run(*args, **kwargs)
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/bases.py", line 538, in downloadWrapperSingle
    res = self._searchForElement(*args, **kwargs)
  File "/usr/local/xdm/var/plugins/Indexer/NewznabXML-nl_avdstelt_newznabXML-0_2/NewznabXML.py", line 72, in searchForElement
    response = xmltodict.parse(urllib.urlopen(r.url).read())
  File "/usr/local/xdm/var/plugins/Indexer/NewznabXML-nl_avdstelt_newznabXML-0_2/pluginRootLibarys/xmltodict/xmltodict.py", line 237, in parse
    parser.Parse(xml_input, True)
ExpatError: mismatched tag: line 8, column 2

New value:[]
Traceback:
Traceback (most recent call last):
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/meta.py", line 160, in outer
    return run(*args, **kwargs)
  File "/volume1/@appstore/xdm/share/XDM/xdm/plugins/bases.py", line 538, in downloadWrapperSingle
    res = self._searchForElement(*args, **kwargs)
  File "/usr/local/xdm/var/plugins/Indexer/NewznabXML-nl_avdstelt_newznabXML-0_2/NewznabXML.py", line 72, in searchForElement
    response = xmltodict.parse(urllib.urlopen(r.url).read())
  File "/usr/local/xdm/var/plugins/Indexer/NewznabXML-nl_avdstelt_newznabXML-0_2/pluginRootLibarys/xmltodict/xmltodict.py", line 237, in parse
    parser.Parse(xml_input, True)
ExpatError: mismatched tag: line 8, column 2
