### ISSUE TITLE
Installing with Py 2.7.3 on Win 8 x64

### ISSUE THREAD

**Issue by tarnalcock** [lad1337/XDM#189]
I get the following error output:
> Traceback (most recent call last):
>  File "D:\AppHolder\XDM\setup.py", line 676, in <module>
>    main()
>  File "D:\AppHolder\XDM\setup.py", line 642, in main
>    result = buildWIN(buildParams)
>  File "D:\AppHolder\XDM\setup.py", line 267, in buildWIN
>    p = subprocess.Popen([ sys.executable, 'setup.py' ], cwd=auto_process_dir)
>  File "C:\Python27\lib\subprocess.py", line 679, in __init__
>    errread, errwrite)
>  File "C:\Python27\lib\subprocess.py", line 896, in _execute_child
>    startupinfo)
>WindowsError: [Error 267] The directory name is invalid

I have googled quite a bit. I am not really familier with Python but I did fiddle aroudn with the popen function in subprocess.py. None of the suggestions I found nor my own tweaks resolved this. 

I also tried executing all command as administrator in case it was permissions related. No luck.

**Comment by sirbishop** [comment]
I get this as well...

Traceback (most recent call last):
  File "setup.py", line 676, in <module>
    main()
  File "setup.py", line 642, in main
    result = buildWIN(buildParams)
  File "setup.py", line 267, in buildWIN
    p = subprocess.Popen([ sys.executable, 'setup.py' ], cwd=auto_process_dir)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 267] The directory name is invalid

I however have not messed with any functions, but I have googled the crap out of it...
