### ISSUE TITLE
XDM won't start

### ISSUE THREAD

**Issue by sirbishop** [lad1337/XDM#190]
So, I've tried to run the setup.py (which bombs with an error that I have reported in a different thread) but for giggles, I try to start XDM and these are my results.  My google-fu has not resulted in any real help.

D:\xdm>python xdm.py
    ←[32;1mINFO←[0m| 2015-03-05 13:34:04.196000: Starting XDM Zim 0.5.18
    ←[32;1mINFO←[0m| 2015-03-05 13:34:04.211000: Logfile path is ##xdm_path##\xd
m.log
    ←[32;1mINFO←[0m| 2015-03-05 13:34:04.276000: Loading/searching system plugin
s
    ←[32;1mINFO←[0m| 2015-03-05 13:34:06.885000: Pylint Score for SystemConfig i
s 9.34
    ←[32;1mINFO←[0m| 2015-03-05 13:34:06.971000: Using i18n path D:\xdm\i18n
    ←[32;1mINFO←[0m| 2015-03-05 13:34:06.982000: Instaling language "en_US <lad1
337@gmail.com>"
    ←[32;1mINFO←[0m| 2015-03-05 13:34:06.992000: CoreUpdate is working with vers
ion 0.5.18 on Git
    ←[32;1mINFO←[0m| 2015-03-05 13:34:07.024000: Loading/searching all plugins
    ←[32;1mINFO←[0m| 2015-03-05 13:34:07.382000: Pylint Score for SystemConfig i
s 9.34
    ←[32;1mINFO←[0m| 2015-03-05 13:34:07.949000: Pylint Score for RegEx is 9.69
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.108000: Pylint Score for Replace is 10.
00
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.192000: Pylint Score for Umlaute is 10.
00
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.306000: Pylint Score for NZB is 10.00
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.412000: Pylint Score for Torrent is 10.
00
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.552000: Stopping all tasks
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.554000: Checking migrate functions with
 last known version: (0, 5, 18) and cur version: (0, 5, 18)
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.559000: Setting up download status chec
ker scheduler every 180 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.586000: Setting up search scheduler eve
ry 43200 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.601000: Setting up mediaadder scheduler
 every 180 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.615000: Setting up news feed scheduler
every 21600 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.625000: Setting up plugin repo / plugin
 update scheduler every 43200 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.635000: Setting up garbage collector sc
heduler every 86400 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.647000: Setting up core update schedule
r every 43200 seconds
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.660000: Generating CherryPy configurati
on
    ←[32;1mINFO←[0m| 2015-03-05 13:34:08.671000: Starting the XDM http web serve
r
Traceback (most recent call last):
  File "xdm.py", line 321, in <module>
    main()
  File "xdm.py", line 287, in main
    app.startWebServer()
  File "xdm.py", line 254, in startWebServer
    cherrypy.server.start()
  File "C:\Python27\lib\site-packages\cherrypy\_cpserver.py", line 167, in start

    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "C:\Python27\lib\site-packages\cherrypy\_cpserver.py", line 158, in https
erver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "C:\Python27\lib\site-packages\cherrypy\_cpwsgi_server.py", line 43, in _
_init__
    accepted_queue_timeout=self.server_adapter.accepted_queue_timeout,
TypeError: __init__() got an unexpected keyword argument 'accepted_queue_size'

**Comment by Deltron216** [comment]
I'm getting the same error....


C:\Users\Del\Documents\GitHub\XDM\XDM>python XDM.py
    ←[32;1mINFO←[0m| 2015-05-21 12:06:30.691000: Starting XDM Zim 0.5.18
    ←[32;1mINFO←[0m| 2015-05-21 12:06:30.697000: Logfile path is ##xdm_path##\xd
m.log
    ←[32;1mINFO←[0m| 2015-05-21 12:06:31.038000: Loading/searching system plugin
s
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.017000: Pylint Score for SystemConfig i
s 9.34
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.293000: Using i18n path C:\Users\Del\Do
cuments\GitHub\XDM\XDM\i18n
 ←[35;1mWARNING←[0m| 2015-05-21 12:06:32.297000: No language file found that mat
ches None. your locale ('English_United States', '1252')
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.300000: Trying to install language en_U
S as fallback
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.303000: Setting language to en_US becau
se of fallback
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.325000: Instaling language "en_US <lad1
337@gmail.com>"
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.329000: CoreUpdate is working with vers
ion 0.5.18 on Git
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.379000: Setting extra plugin path to C:
\Users\Del\Documents\GitHub\XDM\XDM\plugins
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.394000: Loading/searching all plugins
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.477000: Pylint Score for SystemConfig i
s 9.34
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.686000: Pylint Score for RegEx is 9.69
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.775000: Pylint Score for Replace is 10.
00
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.826000: Pylint Score for Umlaute is 10.
00
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.870000: Pylint Score for NZB is 10.00
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.905000: Pylint Score for Torrent is 10.
00
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.959000: Stopping all tasks
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.960000: Checking migrate functions with
 last known version: (0, 4, 18) and cur version: (0, 5, 18)
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.962000: Setting up download status chec
ker scheduler every 180 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.965000: Running migrate function migrat
e_0_4_19
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.968000: Setting up search scheduler eve
ry 43200 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.973000: Setting up mediaadder scheduler
 every 180 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.977000: Setting up news feed scheduler
every 21600 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.980000: Setting up plugin repo / plugin
 update scheduler every 43200 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.983000: Setting up garbage collector sc
heduler every 86400 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.986000: Setting up core update schedule
r every 43200 seconds
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.989000: Generating CherryPy configurati
on
    ←[32;1mINFO←[0m| 2015-05-21 12:06:32.992000: Starting the XDM http web serve
r
Traceback (most recent call last):
  File "XDM.py", line 321, in <module>
    main()
  File "XDM.py", line 287, in main
    app.startWebServer()
  File "XDM.py", line 254, in startWebServer
    cherrypy.server.start()
  File "C:\Python27\lib\site-packages\cherrypy\_cpserver.py", line 167, in start

    self.httpserver, self.bind_addr = self.httpserver_from_self()
  File "C:\Python27\lib\site-packages\cherrypy\_cpserver.py", line 158, in https
erver_from_self
    httpserver = _cpwsgi_server.CPWSGIServer(self)
  File "C:\Python27\lib\site-packages\cherrypy\_cpwsgi_server.py", line 43, in _
_init__
    accepted_queue_timeout=self.server_adapter.accepted_queue_timeout,
TypeError: __init__() got an unexpected keyword argument 'accepted_queue_size'

**Comment by lad1337** [comment]
looks like you have the wrong version of cheerypy globally installed ... create a clean virtualenv and activate it ... then run xdm 

fyi this is not a bug but rather a way you can update the used libs without changing the code
... not truly pythonic but also serves a way to ship xdm with all dependencies

**Comment by Deltron216** [comment]
What version of Cherry.py shoud be installed?

I just grabbed the latest one

Alternatively, If I wanted to reinstall, what files can I back up so that my watchlists are preserved?

Thanks,
